// WarrenWise Youth Animal Training Academy - Core Constants & Configuration

export const APP_INFO = {
  name: "WarrenWise Youth Animal Training Academy",
  shortName: "Animal Academy",
  workingTitle: "4-H Animal Training Academy",
  version: "1.0.0",
  tagline: "Empowering Youth Animal Project Success Through Mastery, Care & Character"
};

// CRITICAL ACCURACY & LEGAL DISCLAIMERS
export const LEGAL_DISCLAIMERS = {
  general: "WarrenWise Youth Animal Training Academy is an independent educational training platform. This application is NOT affiliated with, endorsed by, sponsored by, or an official replacement for the National 4-H Council, USDA National Institute of Food and Agriculture (NIFA), American Rabbit Breeders Association (ARBA), Youth for the Quality Care of Animals (YQCA), or any state/county Cooperative Extension service.",
  veterinary: "EDUCATIONAL OBSERVATION & PREVENTION ONLY: This app and its AI coaches do not provide veterinary diagnoses, prescriptions, treatment protocols, or medication dosages. Always consult a licensed veterinarian or local Extension specialist for sick or injured animals.",
  localRules: "Local project requirements, fair weigh-in rules, age cutoffs, and exhibition classifications vary by state, county, and fair board. Always verify specific requirements with your local 4-H club leader, FFA advisor, or county extension agent.",
  certificates: "Mastery badges and certificates generated by this application verify completion of educational modules within this platform only. They do not constitute official county, state, national, or industry certifications."
};

// AGE DIVISIONS
export const AGE_DIVISIONS = {
  cloverbud: {
    id: 'cloverbud',
    name: 'Cloverbud / Explorer',
    ageRange: 'Ages 5–8',
    readingLevel: 'Early Reader / Visual',
    tone: 'Gentle, enthusiastic, curiosity-driven',
    maxQuizLength: 4,
    passThresholdPercent: 75,
    lowStakes: true,
    description: 'Exploratory, picture-based learning focused on kindness to animals, gentle touch, and basic needs.'
  },
  junior: {
    id: 'junior',
    name: 'Junior Division',
    ageRange: 'Ages 9–11',
    readingLevel: 'Fundamental / Clear',
    tone: 'Supportive, instructional, encouraging',
    maxQuizLength: 6,
    passThresholdPercent: 80,
    lowStakes: false,
    description: 'Step-by-step handling, breed basics, daily chore schedules, healthy signs, and showmanship entry.'
  },
  intermediate: {
    id: 'intermediate',
    name: 'Intermediate Division',
    ageRange: 'Ages 12–14',
    readingLevel: 'Applied Practical',
    tone: 'Engaging, coaching, detail-oriented',
    maxQuizLength: 8,
    passThresholdPercent: 85,
    lowStakes: false,
    description: 'Breed body types, disqualifications, feed nutrition components, biosecurity protocols, and record math.'
  },
  senior: {
    id: 'senior',
    name: 'Senior Division',
    ageRange: 'Ages 15–18',
    readingLevel: 'Advanced / Pre-Judge',
    tone: 'Professional coach, rigorous, analytical',
    maxQuizLength: 10,
    passThresholdPercent: 85,
    lowStakes: false,
    description: 'Standard of Perfection deep dives, genetics, oral judging reasons, barn management, and ethical leadership.'
  }
};

// USER ROLES
export const USER_ROLES = {
  youth: {
    id: 'youth',
    title: 'Youth Learner',
    description: 'Learn modules, complete drills, ask WarrenWise Trainer, earn badges and certificates.'
  },
  parent: {
    id: 'parent',
    title: 'Parent / Guardian',
    description: 'Supervise minor learner, grant coach permissions, review progress and safety settings.'
  },
  coach: {
    id: 'coach',
    title: '4-H Leader / Project Coach',
    description: 'Manage club roster, assign training modules, conduct barn observation checklists, review heatmaps.'
  },
  admin: {
    id: 'admin',
    title: 'Academy Administrator / Root',
    description: 'Review & approve knowledge content, monitor AI safety logs, feature flags, learning analytics.'
  }
};

// 9 STANDARDIZED MODULE TEMPLATE KEYS
export const STANDARD_MODULE_TOPICS = [
  { id: 'basics_breeds', order: 1, title: 'Basics & Breeds', icon: 'Compass', color: 'emerald' },
  { id: 'daily_care', order: 2, title: 'Daily Care & Housing', icon: 'Home', color: 'teal' },
  { id: 'nutrition', order: 3, title: 'Nutrition Principles', icon: 'Apple', color: 'amber' },
  { id: 'health_biosecurity', order: 4, title: 'Health Observation & Biosecurity', icon: 'ShieldAlert', color: 'rose', requiresSafetyReview: true },
  { id: 'handling_welfare', order: 5, title: 'Handling & Welfare', icon: 'HeartHandshake', color: 'indigo', requiresSafetyReview: true },
  { id: 'record_keeping', order: 6, title: 'Record Keeping & Budgeting', icon: 'ClipboardList', color: 'cyan' },
  { id: 'showmanship', order: 7, title: 'Showmanship Foundations', icon: 'Award', color: 'purple' },
  { id: 'ethics_character', order: 8, title: 'Ethics & Character (Head, Heart, Hands, Health)', icon: 'Sparkles', color: 'yellow' },
  { id: 'communication_goals', order: 9, title: 'Project Communication & Goal Setting', icon: 'Target', color: 'blue' }
];

// KNOWLEDGE GOVERNANCE TIERS & WORKFLOW
export const CONTENT_STATUSES = {
  DRAFT: 'draft',
  IN_REVIEW: 'in_review',
  APPROVED: 'approved',
  ARCHIVED: 'archived'
};

export const KNOWLEDGE_TIERS = {
  TIER_1_OFFICIAL: 'Tier 1: Approved Curriculum & Extension Standards',
  TIER_2_COMMUNITY: 'Tier 2: Verified Educator Submissions',
  TIER_3_DRAFT: 'Tier 3: Unapproved Draft (Staff View Only)'
};

// DEFAULT FEATURE FLAGS
export const INITIAL_FEATURE_FLAGS = {
  aiTrainerEnabled: true,
  cloverbudAudioPrompts: true,
  barnOfflineMode: true,
  showmanshipOralStudio: true,
  skillathonDrills: true,
  ethicsScenarios: true,
  parentConsentEnforced: true,
  poultryPackPreview: true,
  goatsPackPreview: true,
  confettiCelebrations: true
};
